--[[
Map Tools: alias definitions

Copyright © 2012-2020 Hugo Locurcio and contributors.
Licensed under the zlib license. See LICENSE.md for more information.
--]]

minetest.register_alias("adminpick", "maptools:pick_admin")
minetest.register_alias("adminpickaxe", "maptools:pick_admin")
minetest.register_alias("admin_pick", "maptools:pick_admin")
minetest.register_alias("admin_pickaxe", "maptools:pick_admin")
minetest.register_alias("pick_admin", "maptools:pick_admin")
minetest.register_alias("pickaxe_admin", "maptools:pick_admin")
minetest.register_alias("pickadmin", "maptools:pick_admin")
minetest.register_alias("pickaxeadmin", "maptools:pick_admin")
minetest.register_alias("adminpickdrops", "maptools:pick_admin_with_drops")
minetest.register_alias("adminpickaxedrops", "maptools:pick_admin_with_drops")
minetest.register_alias("admin_pick_drops", "maptools:pick_admin_with_drops")
minetest.register_alias("admin_pickaxe_drops", "maptools:pick_admin_with_drops")
minetest.register_alias("pick_admin_drops", "maptools:pick_admin_with_drops")
minetest.register_alias("pickaxe_admin_drops", "maptools:pick_admin_with_drops")
minetest.register_alias("pickadmindrops", "maptools:pick_admin_with_drops")
minetest.register_alias("pickaxeadmindrops", "maptools:pick_admin_with_drops")
minetest.register_alias("infinitefuel", "maptools:infinitefuel")
minetest.register_alias("infinite_fuel", "maptools:infinitefuel")
minetest.register_alias("ifuel", "maptools:infinitefuel")
minetest.register_alias("superapple", "maptools:superapple")
minetest.register_alias("super_apple", "maptools:superapple")
minetest.register_alias("sapple", "maptools:superapple")
minetest.register_alias("nobuild", "maptools:nobuild")
minetest.register_alias("nointeract", "maptools:nointeract")
minetest.register_alias("damage_1", "maptools:damage_1")
minetest.register_alias("damage_2", "maptools:damage_2")
minetest.register_alias("damage_3", "maptools:damage_3")
minetest.register_alias("damage_4", "maptools:damage_4")
minetest.register_alias("damage_5", "maptools:damage_5")
minetest.register_alias("pusher_1", "maptools:pusher_1")
minetest.register_alias("pusher_2", "maptools:pusher_2")
minetest.register_alias("pusher_3", "maptools:pusher_3")
minetest.register_alias("pusher_4", "maptools:pusher_4")
minetest.register_alias("pusher_5", "maptools:pusher_5")
minetest.register_alias("pusher_6", "maptools:pusher_6")
minetest.register_alias("pusher_7", "maptools:pusher_7")
minetest.register_alias("pusher_8", "maptools:pusher_8")
minetest.register_alias("pusher_9", "maptools:pusher_9")
minetest.register_alias("pusher_10", "maptools:pusher_10")
minetest.register_alias("killblock", "maptools:kill")
minetest.register_alias("kill_block", "maptools:kill")
minetest.register_alias("lightblock", "maptools:lightblock")
minetest.register_alias("light_block", "maptools:lightblock")
minetest.register_alias("lightbulb", "maptools:lightbulb")
minetest.register_alias("light_bulb", "maptools:lightbulb")
minetest.register_alias("playerclip", "maptools:playerclip")
minetest.register_alias("player_clip", "maptools:playerclip")
minetest.register_alias("pclip", "maptools:playerclip")
minetest.register_alias("fullclip", "maptools:fullclip")
minetest.register_alias("full_clip", "maptools:fullclip")
minetest.register_alias("fclip", "maptools:fullclip")
minetest.register_alias("full_clip", "maptools:fullclip")
minetest.register_alias("full_clip_face", "maptools:fullclip_face")
minetest.register_alias("fullclip_face", "maptools:fullclip_face")
minetest.register_alias("fullclipface", "maptools:fullclip_face")
minetest.register_alias("player_clip_bottom", "maptools:playerclip_bottom")
minetest.register_alias("playerclip_bottom", "maptools:playerclip_bottom")
minetest.register_alias("playerclipbottom", "maptools:playerclip_bottom")
minetest.register_alias("player_clip_top", "maptools:playerclip_top")
minetest.register_alias("playerclip_top", "maptools:playerclip_top")
minetest.register_alias("playercliptop", "maptools:playerclip_top")
minetest.register_alias("permanentfire", "maptools:permanent_fire")
minetest.register_alias("permanent_fire", "maptools:permanent_fire")
minetest.register_alias("pfire", "maptools:permanent_fire")
minetest.register_alias("fakefire", "maptools:fake_fire")
minetest.register_alias("fake_fire", "maptools:fake_fire")
minetest.register_alias("ffire", "maptools:fake_fire")
minetest.register_alias("igniter", "maptools:igniter")

minetest.register_alias("maptools:stone", "default:stone_u")
minetest.register_alias("maptools:tree", "default:tree_u")
minetest.register_alias("maptools:cobble", "default:cobble_u")
minetest.register_alias("maptools:wood", "default:wood_u")
minetest.register_alias("maptools:sand", "default:sand_u")
minetest.register_alias("maptools:gravel", "default:gravel_u")
minetest.register_alias("maptools:brick", "default:brick_u")
minetest.register_alias("maptools:dirt", "default:dirt_u")
minetest.register_alias("maptools:glass", "default:glass_u")
minetest.register_alias("maptools:sandstone", "default:sandstone_u")
minetest.register_alias("maptools:desert_stone", "default:desert_stone_u")
minetest.register_alias("maptools:desertstone", "default:desert_stone_u")
minetest.register_alias("maptools:desert_sand", "default:desert_sand_u")
minetest.register_alias("maptools:desertsand", "default:desert_sand_u")
minetest.register_alias("maptools:leaves", "default:leaves_u")
minetest.register_alias("maptools:grass", "default:grass_u")
minetest.register_alias("maptools:mossycobble", "default:mossycobble_u")

minetest.register_alias("stone_u", "default:stone_u")
minetest.register_alias("tree_u", "default:tree_u")
minetest.register_alias("cobble_u", "default:cobble_u")
minetest.register_alias("wood_u", "default:wood_u")
minetest.register_alias("sand_u", "default:sand_u")
minetest.register_alias("gravel_u", "default:gravel_u")
minetest.register_alias("brick_u", "default:brick_u")
minetest.register_alias("dirt_u", "default:dirt_u")
minetest.register_alias("glass_u", "default:glass_u")
minetest.register_alias("sandstone_u", "default:sandstone_u")
minetest.register_alias("desert_stone_u", "default:desert_stone_u")
minetest.register_alias("desertstone_u", "default:desert_stone_u")
minetest.register_alias("desert_sand_u", "default:desert_sand_u")
minetest.register_alias("desertsand_u", "default:desert_sand_u")
minetest.register_alias("leaves_u", "default:leaves_u")
minetest.register_alias("grass_u", "default:grass_u")
minetest.register_alias("fullgrass", "maptools:fullgrass")
minetest.register_alias("fullgrass_u", "maptools:fullgrass")
minetest.register_alias("mossycobble_u", "default:mossycobble_u")
minetest.register_alias("mossy_cobble_u", "default:mossycobble_u")


